# This can be a json as well.
CATEGORIES = {
    "women": [
        "tops",
        "dresses",
        "shirts-and-blouses",
        "blazers-and-waistcoats",
        "loungewear",
        "nightwear",
        "socks-and-tights",
        "trousers",
        "jackets-and-coats",
        "blazers-and-waistcoats",
        "jeans",
        "shoes",
        "skirts",
        "jumpsuits-rompers",
        "sportswear",
        "swimwear",
        "shorts",
        "maternity-wear",
        "lingerie",
        "care-products",
        "beauty",
        "hoodies-sweatshirts",
        "accessories",
        "cardigans-and-jumpers",
        "plus-sizes",
    ],
    "men": [
        "t-shirts-and-tank-tops",
        "pants",
        "shirts",
        "cardigans-sweaters",
        "hoodies-sweatshirts",
        "blazers-and-suits",
        "jackets-and-coats",
        "jeans",
        "accessories",
        "shoes",
        "shorts",
        "swimwear",
        "sportswear",
        "underwear",
        "nightwear-loungewear",
        "socks",
        "care-products",
    ],
    "babies": [
        "clothing",
        "outerwear",
        "accessories",
        "shoes",
        "costumes",
    ],
    "kids": [
        "clothing",
        "outerwear",
        "accessories",
        "shoes",
        "costumes",
    ],
}
