data:
  path: ../image_store
training:
  epochs: 100
  batch_size: 128
model:
  num_features: 512
  projection_hidden_dim: 512
  output_dim: 512
  pred_hidden_dim: 128
  backbone: resnet18
  criterion: NTXentLoss
optimizer:
  optimizer_name: SGD
  momentum: 0.9
  start_lr: 0.05
  weight_decay: 5e-4
seed: 42
input_size: 256
test_size: 0.3
device: cuda
num_workers: 0
out_dim: 512
run_name: effb3-run-1
